### ISSUE TITLE
Database and functionality

### ISSUE THREAD

**Issue by SlimeDog** [broccolai/PureTickets#1]
Only two tables in the database:
```
sql> .tables
blocked  scores
sql> .schema blocked
CREATE TABLE blocked (uuid TEXT);
sql> .schema scores
CREATE TABLE scores (year INTEGER, month TEXT, player TEXT, points INTEGER);
```
What does this have to do with tickets? I created a ticket, and there is nothing in the database. In fact, the database contains no persistent storage for
- ticket text
- ticket status
- ticket owner
- ticket responder
- ticket location

**Comment by SlimeDog** [comment]
Spigot 1.15.1
PureTickets 1.5

Where are the tickets stored?

**Comment by broccolai** [comment]
Added in 2.0
