### ISSUE TITLE
Ticket numbering inconsistent

### ISSUE THREAD

**Issue by SlimeDog** [broccolai/PureTickets#2]
PureTickets 2.0.1

```
/ti list
==== ALL TICKETS ====
...
_SlimeDog
#2 - thanks.
#3 - Help me please!
```
Tab-completion demands 1 or 2 for index on _SlimeDog.
```
/ti show _SlimeDog 
1   2 
/ti show _SlimeDog 2
==== TICKET 3 ====
Sender: _SlimeDog
Picker: PLAYER_NAME_ELIDED
Date Opened: 2020-05-14 16:42:17
Current Message: Help me please!
```

- Ticket index is 3 in the database
- **/ticket list** displays #3
- Commands -- for example **/ticket show** -- require index 2 (tickets 2 and 3 are the selected player)

It needs to be one or the other. IMHO, the commands should use the database index, without the playerName. For example
```
/ticket show 3
```
instead of
```
/ticket show _SlimeDog 2
```

**Comment by broccolai** [comment]
Yeah I was split between using the index of which ones are currently in and the id of the ticket, I was worried that it'd become tedious typing a long number.  I'll think about moving all the commands to just be their id but `/ticket show _SlimeDog` will show the most recent ticket by that person which I think will be useful for most staff interactions. 

Either way I'll migrate the endings to be the ticket index now

**Comment by SlimeDog** [comment]
Sounds good.

You might consider making the id in a list clickable, which would display the relevant show command, which could then be executed. Sort of the way /locate works to produce tp commands. Just a thought.

**Comment by broccolai** [comment]
Didn't even think of making things clickable, that's a great idea. I'll work on that when the rest of the bugs are fixed

**Comment by broccolai** [comment]
Added
