### ISSUE TITLE
Feature request: Pick other staffmembers

### ISSUE THREAD

**Issue by RogerAntonio** [broccolai/PureTickets#7]
As a staff member, I want to be able to assign (pick) other staff members onto tickets.

Example:
`/ticket pick <ticket id>` Assigns a ticket to myself.
`/ticket pick <ticket id> [staff member]` Assigns ticket to another staff member

Permission:
`tickets.staff.pick.others`

**Comment by broccolai** [comment]
Done in 2.1.2
