### ISSUE TITLE
Feature request: Commands

### ISSUE THREAD

**Issue by SlimeDog** [broccolai/PureTickets#8]
I would like the ability to localize the commands. For example, I would prefer
- **assign** for **pick**
- **resolve** for **done-mark**

**Comment by broccolai** [comment]
Already an option in the newer versions, it's in config.yml. You need to restart after changing them though, /tickets reload doesn't work correctly with it. I have added a new command in the latest commit called assign though

**Comment by SlimeDog** [comment]
Oh, good. Thanks.
